# Case Study on Testing of Hypothesis

IMPORTING LIBRARIES

In [20]:
import scipy.stats as stats
import pandas as pd
import numpy as np
from scipy.stats import ttest_rel


import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

IMPORT DATA FROM CSV

In [21]:
dataset=pd.read_csv('Sales_add.csv')
dataset.tail()

Month      Region      Manager  Sales_before_digital_add(in $)  \
17  Month-18  Region - C  Manager - B                          167996   
18  Month-19  Region - B  Manager - A                          132135   
19  Month-20  Region - A  Manager - B                          152493   
20  Month-21  Region - B  Manager - A                          147425   
21  Month-22  Region - A  Manager - C                          130263   

    Sales_After_digital_add(in $)  
17                         191517  
18                         227040  
19                         212579  
20                         263388  
21                         243020

In [22]:
dataset.isnull().sum()

Month                             0
Region                            0
Manager                           0
Sales_before_digital_add(in $)    0
Sales_After_digital_add(in $)     0
dtype: int64

In [23]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


In [24]:
dataset.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

ABOUT DATA

1. The data is about a company  which started to invest in digital marketing as a new way of their product
   promotions.
2. No values are missing.
3. Data includes sales of the company in consecutive 22 months in the Regions A,B,C(Before and After digital ads)
4. Significant increase in sales can be observed after the  promotion through digital advertisement.

# ● The company wishes to clarify whether there is any increase in sales after stepping into digital marketing

Setting Hypothesis
H0:There is no increase in sales of the  company after it stepped into digital marketing(p>0.05)
H1:There is increase in sales of the company after it stepped into digital marketing(p<=0.05)

In [26]:
before,after=stats.ttest_rel(dataset['Sales_before_digital_add(in $)'], dataset['Sales_After_digital_add(in $)'])
print('statistic value is %0.3f'%before)
print('p-value is %0.12f' %after)

statistic value is -12.091
p-value is 0.000000000063


FINDINGS

Since p-value is <0.05 ,we reject null hypothesis and accept the alternative hypothesis.
Which means,There is increase in sales of the  company after it stepped into digital marketing.

# ● The company needs to check whether there is any dependency between the features “Region” and “Manager”.

Setting Hypothesis

H0:There is some dependency between the features “Region” and “Manager”.

H1:There is no  dependency between the features “Region” and “Manager”.


In [27]:
dataset_table=pd.crosstab(dataset['Region'],dataset['Manager'])
print(dataset_table)


Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1


In [28]:
dataset_table.values 

array([[4, 3, 3],
       [4, 1, 2],
       [1, 3, 1]], dtype=int64)

In [29]:

Observed_Values = dataset_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [30]:
val=stats.chi2_contingency(dataset_table)

In [31]:
Expected_Values=val[3]
Expected_Values

array([[4.09090909, 3.18181818, 2.72727273],
       [2.86363636, 2.22727273, 1.90909091],
       [2.04545455, 1.59090909, 1.36363636]])

In [32]:
no_of_rows=len(dataset_table.iloc[0:3,0])
no_of_columns=len(dataset_table.iloc[0,0:3])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 4


In [33]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 2.921995464852608


In [34]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 9.487729036781154


In [35]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.5709629929220089
Significance level:  0.05
Degree of Freedom:  4
p-value: 0.5709629929220089


In [40]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is some dependency between the features “Region” and “Manager”")
else:
    print("Retain H0,There is no dependency between the features “Region” and “Manager” ")
    
if p_value<=alpha:
    print("Reject H0,There is some dependency between the features “Region” and “Manager”")
else:
    print("Retain H0,There is no dependency between the features “Region” and “Manager” ")

Retain H0,There is no dependency between the features “Region” and “Manager” 
Retain H0,There is no dependency between the features “Region” and “Manager” 


In [ ]:
FINDINGS
There is no dependency between the features “Region” and “Manager”.